config/routes.rb
Rails.application.routes.draw do
  get 'dummy/index'

  resources :comments
  root 'dummy#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :set_comment, only: [:destroy, :edit, :update, :show]
    
    def index
        @comments = Comment.all
    end   
    
    def create
        @comment = Comment.new(comment_params)
        @comment.save
    end 

    def edit
    end    

    def update
        @comment.update(comment_params)
    end   

    def show
    end     

    def destroy
        @comment.destroy
    end    

    private

    def set_comment
        @comment = Comment.find(params[:id])
    end

    def comment_params
        params.require(:comment).permit(:content)
    end    
end

app/controllers/dummy_controller.rb
class DummyController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dummy_helper.rb
module DummyHelper
end

app/views/comments/_comment.html.erb
<li id='comment_<%= comment.id %>'>
<%= render 'inner_comment', comment: comment %>
</li>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |f| %>
    <div class='form-group'>
        <%= f.text_field :content, class: 'form-control d-inline w-75 p-0 m-0'%>
        <%= f.submit 'actualizar', class: 'btn btn-warning d-inline' %>
    </div>
<%end%>

app/views/comments/_inner_comment.html.erb
<%= comment.content %>
<%= link_to 'Ver', comment_path(comment), 'data-remote': true %>
<%= link_to 'Actualizar', edit_comment_path(comment), 'data-remote': true %>
<%= link_to 'Eliminar', comment_path(comment), data: {remote: true, confirm: 'Segurolas?'}, method: :delete %>

app/views/comments/create.js.erb
$('ul').append('<%= j render @comment %>')
$('#comment_content').val('')

app/views/comments/destroy.js.erb
$('#comment_<%= @comment.id %>').fadeOut(700)

app/views/comments/edit.js.erb
$('.modal').modal()
$('.modal-body').html('<%= j render 'form', comment: @comment %>')
$('.modal-title').html('Actualizar')

//var form = document.createElement('form');
//var text_input = document.createElement('input');
//var id_input = document.createElement('input');
//var button = document.createElement('button');
//
//id_input.hidden = true;
//button.type = 'submit'
//id_input.value = '<%= @comment.id %>'
// text_input.value = '<%= @comment.content %>'
//text_input.name = 'comment'
//id_input.name = 'comment'
//button.innerText = 'update'
//
//form.appendChild(text_input)
//form.appendChild(id_input)
//form.appendChild(button)
//$('#update').append(form)

app/views/comments/index.js.erb
$('ul').html('')
$('ul').append('<%= j render @comments%>')

app/views/comments/show.js.erb
$('.modal').modal()
$('.modal-body').html('<%=  @comment.content %>')
$('.modal-title').html('Detalles')

app/views/comments/update.js.erb
$('.modal').modal('hide')
$('#comment_<%= @comment.id %>').html('<%= j render 'inner_comment', comment: @comment %>')

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UjsDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>